name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test.yml@main
    secrets:
      DISCORD_CI_WEBHOOK: ${{ secrets.DISCORD_CI_WEBHOOK }}
    with:
      scheme: KippleUI-Package
      subcommand: build
      platforms: iOS tvOS macOS watchOS
      swift-versions: 5.5 5.6
